version: '3'
services:
  kk-postgres:
    image: postgres:11.5
    container_name: IT-kk-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=kk
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  kk-postgres-it:
    image: postgres:11.5
    container_name: kk-database-it
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=kk-it
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
